version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      eventhubs-emulator:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orchestrator
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EVENTHUB_CONNECTION_STRING=Endpoint=sb://eventhubs-emulator:9092;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;UseDevelopmentEmulator=true;Transport=Kafka
      - EVENTHUB_NAME=orchestrator
    volumes:
      - ./app:/app/app
    networks:
      - eh-emulator
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orchestrator
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eh-emulator
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - eh-emulator
    restart: unless-stopped

  eventhubs-emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - azurite
    networks:
      - eh-emulator

  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    pull_policy: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - eh-emulator

  # RedPanda Console - Kafka UI
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8085:8080" # Map to a different port to avoid conflict with the API
    volumes:
      - ./redpanda.yaml:/etc/redpanda/redpanda.yaml
    environment:
      - CONFIG_FILEPATH=/etc/redpanda/redpanda.yaml
    networks:
      - eh-emulator
    depends_on:
      - eventhubs-emulator
    restart: unless-stopped

networks:
  eh-emulator:
    name: eh-emulator
    driver: bridge

volumes:
  postgres-data:
  redis-data:
